ARM: boards: drop deprecated ddrphy_trained_csr arrays
The members are deprecated and ignored by the DDR PHY driver. GCC
doesn't warn about deprecated members in designated initializers,
clang does:

  arch/arm/boards/tqma93xx/lpddr4x_tqma93xxla_timing.c:1477:3: error: 'ddrphy_trained_csr' is deprecated: board-specific data here is ignored in favor of the defaults. You can probably remove the array [-Werror,-Wdeprecated-declarations]

Remove the arrays from the four remaining boards.

Assisted-by: Claude:fable-5
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>