FIT: improve error message when uncompressing non-compressed files
If due to user error, an uncompressed kernel is added into a FIT image,
but compression = "gzip" is specified, a quite cryptic message results:

  ERROR: FIT: cannot handle filetype ARM aarch64 Linux image
  ERROR: FIT: data couldn't be decompressed
  ERROR: Loading dtb image failed with: Function not implemented

Adapt the error messages a bit, so it says instead:

  ERROR: FIT: unsupported compression filetype "aarch64 Linux image"
  ERROR: FIT: gzip data couldn't be decompressed
  ERROR: Loading FIT image failed with: Function not implemented

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>