sandbox: make CC_HAS_LINUX_I386_SUPPORT depend on GCC
CC_HAS_LINUX_I386_SUPPORT enables build for 32-bit with a 64-bit GCC
toolchain. This seems not to work correctly on clang:

  CC      arch/sandbox/os/common.o
  In file included from arch/sandbox/os/common.c:23:
  In file included from /usr/lib/llvm-16/lib/clang/16/include/limits.h:21:
  /usr/include/limits.h:26:10: fatal error:
                               'bits/libc-header-start.h' file not found
  #include <bits/libc-header-start.h>

So disable it for now.

Fixes: f41c4d7c5649 ("Makefile: add LLVM/clang support")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>