bitops: fix missing defintion for DIV_ROUND_UP definitions
Macros like BITS_TO_LONGS defined in <linux/bitops.h> expand to
DIV_ROUND_UP, which isn't defined in the same file.

We can't easily include <linux/math.h> however as this leads to a
recursive file inclusion:

In file included from ./include/asm-generic/div64.h:53,
                 from ./include/linux/math64.h:7,
                 from ./include/linux/math.h:6,
                 from ./include/linux/bitops.h:9,
                 from ./include/clock.h:7,
                 from ./include/console.h:15,
                 from ./include/stdio.h:6,
                 from ./include/common.h:10,
                 from ./common/partitions/dos.c:15:
 ./include/linux/log2.h: In function '__ilog2_u32':
 ./include/linux/log2.h:28:16: error: implicit declaration of function 'fls'
		[-Wimplicit-function-declaration]
    28 |         return fls(n) - 1;

Fix this by doing it like Linux does and use the UAPI
__KERNEL_DIV_ROUND_UP definition instead.

Signe-off-by: Ahmad Fatoum <a.fatoum@barebox.org>