test: py: add dry run check for FIT image
A dry run should not alter system state in a way that would inhibit
normal operation or repeated dry runs.

The FIT image boot in the test suite, however, reduces the VFS root's
reference count beyond the initial value before the bootm.

This leads to a warning on boot that can be reproduced by repeating the
dry run multiple times:

  FAILED test/py/test_fit.py::test_fit_dryrun -
	AssertionError: ['WARNING: at fs/fs.c:255/mntput()!',
			 'WARNING: refcount for mount "/" becomes negative']

Add a regression test for this issue.

Signed-off-by: Ahmad Fatoum <a.fatoum@barebox.org>